#!/usr/bin/env python
#scipt by Techfan 
#
import os
import time
#reboot process
print ("starting the reboot process") 
os.system('irsend SEND_ONCE rc73 KEY_G')
time.sleep(25)
print ("Go to Guide to power on or to ensure process flows")
os.system('irsend SEND_ONCE rc73 KEY_MENU')
time.sleep(15)
print ("Starting crawl to reboot")
os.system('irsend SEND_ONCE rc73 KEY_LEFT')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_DOWN')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_DOWN')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_DOWN')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_DOWN')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_DOWN')
time.sleep(8)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(3)
os.system('irsend SEND_ONCE rc73 KEY_RIGHT')
time.sleep(15)
os.system('irsend SEND_ONCE rc73 KEY_SELECT')
time.sleep(5)
os.system('irsend SEND_ONCE rc73 KEY_SELECT')
time.sleep(5)
print ("Final command to reboot")
os.system('irsend SEND_ONCE rc73 KEY_SEND')
#timing is key, the sweet spot but might need adjusting for others
time.sleep(69)
print ("Starting firmware upgrade sequence")
#upgrade firmware process
os.system('irsend SEND_ONCE rc73 KEY_0')
time.sleep(0.5)
print ("Send 0")
os.system('irsend SEND_ONCE rc73 KEY_2')
time.sleep(0.5)
print ("Send 2")
os.system('irsend SEND_ONCE rc73 KEY_4')
time.sleep(0.5)
print ("Send 4")
os.system('irsend SEND_ONCE rc73 KEY_6')
time.sleep(0.5)
print ("Send 6")
os.system('irsend SEND_ONCE rc73 KEY_8')
time.sleep(0.5)
print ("Send 8")
time.sleep(1)
print ("DONE, HR should be updating")
#enjoy unattended updates  
